# -*- coding: utf-8 -*-
"""AulaPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TY__RTSh_9nVgL07bqKdeva_4wzt_PGn
"""

nome ="Michael"
print(nome)

nome = "Guilherme"
nome

idade = 37
idade

idade = idade + 37

idade

def mais_um_ano(idade):
  print("ta dentro da funcao")
  return idade+1

mais_um_ano(44)

filme1 = "Toy Story"
filme2 = "Xuxa"
filme3 = "Matrix 1"

filmes = ["Toy Story", "Xuxa", "Matrix 1"]
filmes

filmes = [filme1, filme2, filme3]
filmes

def imprime_filmes(filmes_quero_imprimir):
  print("Lista:")
  print(filmes_quero_imprimir)

imprime_filmes

imprime_filmes(filmes)

filmes[0]

filmes[-1] ##ultimo

filmes[-2] ##penultimo

filmes[1:] #um para frente ou -2 pra frente

for filme in filmes:
  print(filme)

def imprime_filmes(filmes_quero_imprimir):
  print("A lista:")
  for filme in filmes_quero_imprimir:
    print (filme)

imprime_filmes (filmes)

dados = {"nome": "Guilherme", "idade":37, "empresa" : "Alura"}
dados

dados [empresa]

dados["empresa"]

