# -*- coding: utf-8 -*-
"""IntroducaoMachineLearning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L6IjFVia4BTTDXUIg-WOmKn-d6Fh4haa
"""

#pelo longo
#perna curta
#faz auau
porco1 = [0, 1, 0]
porco2 = [0, 1, 1]
porco3 = [1, 1, 0]

cachorro1 = [0, 1, 1]
cachorro2 = [1, 0, 1]
cachorro3 = [1, 1, 1]

treino_x = [porco1, porco2, porco3, cachorro1, cachorro2, cachorro3]
treino_y = [1, 1, 1, 0, 0, 0] #1=porco, 0=cachorro

from sklearn.svm import LinearSVC
modelo = LinearSVC()
modelo.fit(treino_x, treino_y)

animal_misterioso = [1, 1, 1]
modelo.predict([animal_misterioso])

misterio1=[1, 1, 1]
misterio2=[1, 1, 0]
misterio3=[0, 1, 1]

teste_x = [misterio1, misterio2, misterio3]
teste_y = [0, 1, 1]

previsoes = modelo.predict(teste_x)
previsoes

from sklearn.metrics import accuracy_score

accuracy_score(teste_y, previsoes)

import pandas as pd
uri = "https://gist.githubusercontent.com/guilhermesilveira/2d2efa37d66b6c84a722ea627a897ced/raw/10968b997d885cbded1c92938c7a9912ba41c615/tracking.csv"
dados = pd.read_csv(uri)
dados.head()

dados.sample(5)

x = dados[["home", "how_it_works", "contact"]]
x.head()

y = dados["bought"]
y.head()

from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
modelo = LinearSVC()

treino_x, teste_x, treino_y, teste_y = train_test_split(x,y)

modelo.fit(treino_x, treino_y)


previsoes = modelo.predict(teste_x)
accuracy_score(teste_y, previsoes)

treino_x.shape

teste_x.shape

